services:
  resilmesh_ap_nats:
    container_name: "NATS"
    hostname: "nats"
    restart: unless-stopped
    build:
      context: "./"
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    networks:
      - resilmesh_network