services:
  resilmesh-ap-nats:
    container_name: "resilmesh-ap-nats"
    hostname: "nats"
    restart: unless-stopped
    build:
      context: "./"
    ports:
      - 4222
      - 8222
      - 6222
    networks:
      - resilmesh_network